name: Mirror Repositories to Codeberg

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    # Allow manual triggering
  push:
    branches: [ main ]
    paths:
      - 'blacklist.txt'
      - '.github/workflows/mirror.yml'

jobs:
  mirror:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests PyGithub gitpython
        
    - name: Run mirroring script
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        CODEBERG_TOKEN: ${{ secrets.CODEBERG_TOKEN }}
        CODEBERG_USERNAME: ${{ secrets.CODEBERG_USERNAME }}
      run: python scripts/mirror.py
      
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: mirror-logs
        path: mirror.log
        retention-days: 30